### PR TITLE
Command

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-controller/14)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 12 files reviewed at latest revision, 8 unresolved discussions.

---

_[js/block-manager.js, line 13 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdTzV0x8t8jQuuauO6:-KMdTzV1yomuHkl74miZ:-678418599) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/block-manager.js#L13)):_

> ``` JavaScript
> 
>   this.blocks = [];
>   let blockElements = document.querySelectorAll("[data-block-index]");
> ```

const で大丈夫よー

---

_[js/block-manager.js, line 22 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdU5_sWIh0qyQSHtYB:-KMdU5_sWIh0qyQSHtYC:-806321199) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/block-manager.js#L22)):_

> ``` JavaScript
>   });
> 
>   eventPublisher.subscribe("availableCommandsCount", (count) => {
> ```

今回の修正箇所ではないけれど、count の括弧はいらなそうです

---

_[js/block.js, line 39 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdUOIBiJX46Ac-TQCQ:-KMdUOIDsAYLss2QgNA5:1828454930) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/block.js#L39)):_

> ``` JavaScript
>   });
> 
>   eventPublisher.subscribe("mode", (newMode) => {
> ```

同様に括弧いらないっすー

---

_[js/block.js, line 48 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdURr-tpYmbPK55TiR:-KMdURr-tpYmbPK55TiS:1055329695) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/block.js#L48)):_

> ``` JavaScript
>   });
> 
>   eventPublisher.subscribe("compile", (args) => {
> ```

ここもー

---

_[js/parser.js, line 11 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdUqVc-rAVRARamDgZ:-KMdUqVdF-gERkjMIfUr:172582582) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/parser.js#L11)):_

> ``` JavaScript
>   }
>   this.logElement = logElement;
>   eventPublisher.subscribe("saveMotion", (motion) => {
> ```

かっこ

---

_[js/parser.js, line 17 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdUwKI39HvVHYwUZvh:-KMdUwKI39HvVHYwUZvi:-522250127) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/parser.js#L17)):_

> ``` JavaScript
>       rawFunction({
>         command: function(commandName, args, time) {
>           let errors = [];
> ```

const でいけると思います

---

_[js/sphero-client.js, line 14 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdV8ukIGJNoTgf4RnX:-KMdV8ukIGJNoTgf4RnY:172582582) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/sphero-client.js#L14)):_

> ``` JavaScript
>       eventPublisher.publish("ws-connected");
>       this.orb.color("red");
>       eventPublisher.subscribe("spheroState", (spheroState) => {
> ```

かっこ

---

_[js/sphero-client.js, line 21 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdVAhCeI_Zqy8fTH_V:-KMdVAhCeI_Zqy8fTH_W:172582582) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/sphero-client.js#L21)):_

> ``` JavaScript
>         }
>       });
>       eventPublisher.subscribe("changeCurrentCommands", (commands) => {
> ```

かっこ

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/14)_

**Comment by shundroid** [comment]
Review status: 0 of 12 files reviewed at latest revision, 8 unresolved discussions.

---

_[js/block-manager.js, line 13 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdTzV0x8t8jQuuauO6:-KMiDVB4sKbHF-p_AJGd:1208707732) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/block-manager.js#L13)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> const で大丈夫よー
> </details>
> なおしました

---

_[js/block-manager.js, line 22 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdU5_sWIh0qyQSHtYB:-KMiDXV-X-dSb1ZUwUZk:1208707732) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/block-manager.js#L22)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> 今回の修正箇所ではないけれど、count の括弧はいらなそうです
> </details>
> なおしました

---

_[js/block.js, line 39 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdUOIBiJX46Ac-TQCQ:-KMiDY6WNJJB78Vjx-z_:1208707732) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/block.js#L39)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> 同様に括弧いらないっすー
> </details>
> なおしました

---

_[js/block.js, line 48 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdURr-tpYmbPK55TiR:-KMiDYg-ClXvp83HBMku:1208707732) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/block.js#L48)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここもー
> </details>
> なおしました

---

_[js/parser.js, line 11 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdUqVc-rAVRARamDgZ:-KMiDZG-mCDmOSxlBMgt:1208707732) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/parser.js#L11)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> かっこ
> </details>
> なおしました

---

_[js/parser.js, line 17 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdUwKI39HvVHYwUZvh:-KMiD_23PVrc6KqvjYrc:1208707732) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/parser.js#L17)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> const でいけると思います
> </details>
> なおしました

---

_[js/sphero-client.js, line 14 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdV8ukIGJNoTgf4RnX:-KMiD_cjtVG1YmieVWkA:1208707732) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/sphero-client.js#L14)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> かっこ
> </details>
> なおしました

---

_[js/sphero-client.js, line 21 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdVAhCeI_Zqy8fTH_V:-KMiDaDa381HCbOBM9Pg:1208707732) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/sphero-client.js#L21)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> かっこ
> </details>
> なおしました

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/14)_

**Comment by dadaa** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/parser.js, line 17 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdUwKI39HvVHYwUZvh:-KMlDFnamhK7_eLSJJZT:576257971) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/parser.js#L17)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> なおしました
> </details>
> ここだけまだ治ってみない

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/14)_

**Comment by shundroid** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/parser.js, line 17 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdUwKI39HvVHYwUZvh:-KMlDrIXKpgGqwg3-oSD:1643701165) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/parser.js#L17)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここだけまだ治ってみない
> </details>
> すみません。直します。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/14)_

**Comment by shundroid** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/parser.js, line 17 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMdUwKI39HvVHYwUZvh:-KMlEGR8m9aZtDHextfK:-2126081218) ([raw file](https://github.com/comozilla/onigo-controller/blob/6d32c84e4bac7996704e8d242452301181a44ab0/js/parser.js#L17)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> すみません。直します。
> </details>
> 直しました

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/14)_

**Comment by dadaa** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/parser.js, line 59 [r3]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMlEZlM3iOPgIkAT9fB:-KMlEZlNXLQWQD9YhEpT:-93253018) ([raw file](https://github.com/comozilla/onigo-controller/blob/7968d9973c6f217f6ab827cadc60d6697f590eb3/js/parser.js#L59)):_

> ``` JavaScript
>     throw new Error("logTypeは正しくありません : " + logType);
>   }
>   let message = rawMessage
> ```

ごめん！ここも const で良さそう！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/14)_

**Comment by shundroid** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/parser.js, line 59 [r3]](https://reviewable.io:443/reviews/comozilla/onigo-controller/14#-KMlEZlM3iOPgIkAT9fB:-KMlF1g2e2gpj2cxIulY:-1483996028) ([raw file](https://github.com/comozilla/onigo-controller/blob/7968d9973c6f217f6ab827cadc60d6697f590eb3/js/parser.js#L59)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ごめん！ここも const で良さそう！
> </details>
> 直しました。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/14)_

**Comment by dadaa** [comment]
Reviewed 8 of 12 files at r1, 3 of 4 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/14)_

**Comment by shundroid** [comment]
ありがとうございました！

**Pull request merged**
