### PR TITLE
Backupできるように

### PR DESCRIPTION
**Pull request by shundroid**
- localStorageに保存して、リロード後にデータが飛ばないように

---

This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-controller/30)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[js/backup.js, line 8 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/30#-KNkA0ULvUt1ZZ76grkq:-KNkA0UMMVCDHQT7OnZ_:343147805) ([raw file](https://github.com/comozilla/onigo-controller/blob/43520c2883deea942282218e6433403f2a134259/js/backup.js#L8)):_

> ``` JavaScript
>   eventPublisher.subscribe("compile", args => {
>     this.motions[args.motion.motionId] = {
>       code: args.motion.motion.motionCode,
> ```

motion.motion って何か不思議な感じねw

---

_[js/backup.js, line 23 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/30#-KNk9g95SMiFebxFBQZe:-KNk9g96J02lNQsJKRCn:1101802455) ([raw file](https://github.com/comozilla/onigo-controller/blob/43520c2883deea942282218e6433403f2a134259/js/backup.js#L23)):_

> ``` JavaScript
>   Object.keys(backup).forEach(motionId => {
>     eventPublisher.publish("saveMotion", {
>       motionId: parseInt(motionId),
> ```

JSON.stringfy するまえの motionId が int だったら、parseInt はいらないかと思います。
いちおう、確認してみてください

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/30)_

**Comment by shundroid** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[js/backup.js, line 8 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/30#-KNkA0ULvUt1ZZ76grkq:-KNkAOGehOX_12llsdmq:-1620293231) ([raw file](https://github.com/comozilla/onigo-controller/blob/43520c2883deea942282218e6433403f2a134259/js/backup.js#L8)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> motion.motion って何か不思議な感じねw
> </details>
> そうですねｗなんでこうなっているんだろう、確認します。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/30)_

**Comment by shundroid** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[js/backup.js, line 23 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/30#-KNk9g95SMiFebxFBQZe:-KNkAtJItXcwUp6wLdt4:-80053184) ([raw file](https://github.com/comozilla/onigo-controller/blob/43520c2883deea942282218e6433403f2a134259/js/backup.js#L23)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> JSON.stringfy するまえの motionId が int だったら、parseInt はいらないかと思います。
> いちおう、確認してみてください
> </details>
> motionId は、stringifyする前、キーに使っていて、
> キーにすると自動的に toString されてしまう気がします。



---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/30)_

**Comment by dadaa** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[js/backup.js, line 23 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/30#-KNk9g95SMiFebxFBQZe:-KNkByFYe9N08pZD9WDi:-1279942238) ([raw file](https://github.com/comozilla/onigo-controller/blob/43520c2883deea942282218e6433403f2a134259/js/backup.js#L23)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> motionId は、stringifyする前、キーに使っていて、
> キーにすると自動的に toString されてしまう気がします。
> 
> 
> 
> </details>
> あ、ごめん、Resolved にしちゃったんだけど、逆に言うと、int にする必要はある？

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/30)_

**Comment by shundroid** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[js/backup.js, line 23 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/30#-KNk9g95SMiFebxFBQZe:-KNkC8wva85UwxHve812:-1203145839) ([raw file](https://github.com/comozilla/onigo-controller/blob/43520c2883deea942282218e6433403f2a134259/js/backup.js#L23)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> あ、ごめん、Resolved にしちゃったんだけど、逆に言うと、int にする必要はある？
> </details>
> block.js の 55 行目、

``` js
    if (args.motion.motionId === this.blockId) {
```

これで比較するときに、motionId が数値じゃないと true にならないです。

あと、saveMotion は、editor.js でも publish していて、
そっちでは数値にしているので、合わせている感じです。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/30)_

**Comment by dadaa** [comment]
Reviewed 1 of 2 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/30)_

**Pull request merged**
