### PR TITLE
Simple command

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-controller/28)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[js/parser.js, line 42 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/28#-KNaRixnxZ3-OM3X4NqG:-KNaRixpicMCmb0n-1QT:225528279) ([raw file](https://github.com/comozilla/onigo-controller/blob/7d836fe6897bcd1022f9805f3d0476f80ceb1189/js/parser.js#L42)):_

> ``` JavaScript
>           validateResult.errors.forEach(error => {
>             this.log(error + " at " + commandName + "()", "error");
>             isError = true;
> ```

isError の代わりに throw させると、if, else がかなり少なくなって綺麗になりそうじゃない？

---

_[js/parser.js, line 74 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/28#-KNaRxZvSeeJqkZPmVOT:-KNaRxZvSeeJqkZPmVOU:-246894075) ([raw file](https://github.com/comozilla/onigo-controller/blob/7d836fe6897bcd1022f9805f3d0476f80ceb1189/js/parser.js#L74)):_

> ``` JavaScript
>       this.log(error.message, "error");
>       console.error(error);
>       isError = true;
> ```

そうすると、この catch でとれるので、isError 変数が不必要にできそう。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/28)_

**Comment by shundroid** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[js/parser.js, line 42 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/28#-KNaRixnxZ3-OM3X4NqG:-KNaSJNeGM5TGbybtq1T:1941960282) ([raw file](https://github.com/comozilla/onigo-controller/blob/7d836fe6897bcd1022f9805f3d0476f80ceb1189/js/parser.js#L42)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> isError の代わりに throw させると、if, else がかなり少なくなって綺麗になりそうじゃない？
> </details>
> そうですね！そうします！

（このブランチの）最初 isError だけ作ってて、
それだとSyntaxErrorとかとれないじゃん！となって、
tryをつけたらわかりにくくなってしまいました。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/28)_

**Comment by shundroid** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[js/parser.js, line 74 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/28#-KNaRxZvSeeJqkZPmVOT:-KNaSapXuPFLVmRR375J:832887645) ([raw file](https://github.com/comozilla/onigo-controller/blob/7d836fe6897bcd1022f9805f3d0476f80ceb1189/js/parser.js#L74)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> そうすると、この catch でとれるので、isError 変数が不必要にできそう。
> </details>
> そうします！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/28)_

**Comment by dadaa** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/parser.js, line 69 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-controller/28#-KNapCM64t0oKTvSz-Ms:-KNapCM86ZLSt2b1nHez:-716539770) ([raw file](https://github.com/comozilla/onigo-controller/blob/d69ec72ca7c2780b25712b3b702733a21881c473/js/parser.js#L69)):_

> ``` JavaScript
>       eventPublisher.publish("compile", { motion, commands });
>       this.log("コードのParseは正しく完了しました。", "success");
>     } catch (error) {
> ```

ここの catch は何を想定しています？

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/28)_

**Comment by shundroid** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/parser.js, line 69 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-controller/28#-KNapCM64t0oKTvSz-Ms:-KNasgcscjOy0EVvz2Ep:988238158) ([raw file](https://github.com/comozilla/onigo-controller/blob/d69ec72ca7c2780b25712b3b702733a21881c473/js/parser.js#L69)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここの catch は何を想定しています？
> </details>
> 上の throw new Error(errors.join("\n")) で出したエラーと、
> rawFunction の SyntaxError、ReferenceErrorです。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/28)_

**Comment by dadaa** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/parser.js, line 69 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-controller/28#-KNapCM64t0oKTvSz-Ms:-KNauxcQWDlRf6EL50P1:-1252582726) ([raw file](https://github.com/comozilla/onigo-controller/blob/d69ec72ca7c2780b25712b3b702733a21881c473/js/parser.js#L69)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> 上の throw new Error(errors.join("\n")) で出したエラーと、
> rawFunction の SyntaxError、ReferenceErrorです。
> </details>
> exception が出るがわかっているなら、検査して、同じように push したいかも。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/28)_

**Comment by dadaa** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/parser.js, line 69 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-controller/28#-KNapCM64t0oKTvSz-Ms:-KNav85k7uQCJnxeRXkK:361684358) ([raw file](https://github.com/comozilla/onigo-controller/blob/d69ec72ca7c2780b25712b3b702733a21881c473/js/parser.js#L69)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> exception が出るがわかっているなら、検査して、同じように push したいかも。
> </details>
> exception が出る場所がわかっているなら、検査して、同じように push したいかも。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/28)_

**Comment by shundroid** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/parser.js, line 69 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-controller/28#-KNapCM64t0oKTvSz-Ms:-KNavMU3QfV9FGgcoOI9:466662171) ([raw file](https://github.com/comozilla/onigo-controller/blob/d69ec72ca7c2780b25712b3b702733a21881c473/js/parser.js#L69)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> exception が出る場所がわかっているなら、検査して、同じように push したいかも。
> </details>
> そのexceptionが出る場所のみにtry-catchをかけるということでしょうか。

rawFunction.applyのところででそうです。引数は先に作っておいて、そのapplyだけtryするようにします。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/28)_

**Comment by dadaa** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/28)_

**Pull request merged**
