### PR TITLE
鬼の画像を変更＆HPバー

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-controller/32)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[css/style.css, line 202 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/32#-KO2uc5d_rWMmOpnlOEm:-KO2uc5eOGp-WjGvdBip:2013905543) ([raw file](https://github.com/comozilla/onigo-controller/blob/687b4a0196c83e07f18fdc1e2d3677da0cecfe48/css/style.css#L202)):_

> ``` CSS
>   padding: 0;
> }
> #playing-mode-banner #hp-bar {
> ```

この上に空行をいれましょ
あと、この指定なら #hp-bar だけで良さそう。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/32)_

**Comment by shundroid** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[css/style.css, line 202 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-controller/32#-KO2uc5d_rWMmOpnlOEm:-KO2vWQLVORGmUDAgzrR:-1483943037) ([raw file](https://github.com/comozilla/onigo-controller/blob/687b4a0196c83e07f18fdc1e2d3677da0cecfe48/css/style.css#L202)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> この上に空行をいれましょ
> あと、この指定なら #hp-bar だけで良さそう。
> </details>
> 直しました！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/32)_

**Comment by shundroid** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_[js/oni-board.js, line 1 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-controller/32#-KO2vfkF7sKGUkod5bfk:-KO2vfkGVXLGdl6fye_t:1413344056) ([raw file](https://github.com/comozilla/onigo-controller/blob/06996e022fa55e086b3898b13ebccc32c35320c4/js/oni-board.js#L1)):_

> ``` JavaScript
> import eventPublisher from "./publisher";
> ```

改行コード間違えたので直します

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/32)_

**Comment by shundroid** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/oni-board.js, line 1 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-controller/32#-KO2vfkF7sKGUkod5bfk:-KO2wC5u8Zr6sW2efgDM:-2126081218) ([raw file](https://github.com/comozilla/onigo-controller/blob/06996e022fa55e086b3898b13ebccc32c35320c4/js/oni-board.js#L1)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> 改行コード間違えたので直します
> </details>
> 直しました

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/32)_

**Comment by dadaa** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/32)_

**Pull request merged**
