### PR TITLE
[WIP] Add change user

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-controller/45)

### CODE REVIEW

**Comment by shundroid** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[js/backup.js, line 18 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF5mZ1b4USwA0d1BNB:-KbF5mZ1b4USwA0d1BNC:b-6p82df) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/backup.js#L18)):*
> ```JavaScript
>       this.set(this.userName, index, backup);
>     });
>     eventPublisher.subscribe("changeUserName", name => {
> ```

ここで userName という名前で受け取れば、↑で新しく publish しなくてもよさそうだけどどうです？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Reviewed 1 of 5 files at r1, 2 of 6 files at r3.
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[js/components/change-user-screen.vue, line 4 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF6FghGcb1s2W2Lqv3:-KbF6FghGcb1s2W2Lqv4:bchk110) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/components/change-user-screen.vue#L4)):*
> ```Vue
>   <div :class="classList">
>     <div id="user-name-inner">
>       <h2>コントローラーの名前を変えよう</h2>
> ```

コントローラーの名前じゃなくてユーザーの名前とかにしたほうがわかりやすいかと

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[js/components/change-user-screen.vue, line 6 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF6QRZa6qwqbVPRma6:-KbF6QRZa6qwqbVPRma7:b-4f9q3c) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/components/change-user-screen.vue#L6)):*
> ```Vue
>       <h2>コントローラーの名前を変えよう</h2>
>       <div id="user-name-zone">
>         <input type="text" id="user-name" placeholder="ここに名前を入力しよう" />
> ```

document.get..... を使わない方法・・

↓の data() のところの return で、userName とかいう state を追加します。
`userName: ""` みたいな

それで、↑の要素に、 `v-model="userName"` という感じで属性を指定します。

そうすると、双方向にデータバインディングをしてくれるので、要素を参照する必要がなくなります。

https://jp.vuejs.org/v2/guide/forms.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[js/components/change-user-screen.vue, line 39 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF6ujlujnN9RJtmmcw:-KbF6ujlujnN9RJtmmcx:b-jkr4of) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/components/change-user-screen.vue#L39)):*
> ```Vue
>   methods :{
>     changeUserName() {
>       appModel.changeUserName(document.getElementById("user-name").value);
> ```

そうするとここは `this.userName` で state を参照できます

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Review status: 3 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[js/components/change-user-screen.vue, line 40 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF7-FuNR5fj8YyIrdQ:-KbF7-FuNR5fj8YyIrdR:b-yqvz1f) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/components/change-user-screen.vue#L40)):*
> ```Vue
>     changeUserName() {
>       appModel.changeUserName(document.getElementById("user-name").value);
>       appModel.changeUserScreenState(false);
> ```

`this.closeUserNameScreen()` のほうが役割としてわかりやすいかも

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[js/backup.js, line 24 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF8PIHTW0rXFsCKrtV:-KbF8PIIMDBRgADq8YBO:bkqeu7u) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/backup.js#L24)):*
> ```JavaScript
>       this.addUserNames(this.userName);
>       this.restore();
>       this.setEmptyBlock(oldUserName);
> ```

うーん、ここでやる処理としては、
1. userName がリストになければ追加する
2. 新しい user の データを restore する
でしょうか

となると、setEmptyBlock はいります？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[js/backup.js, line 22 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF9-EjD_crV9CAV7JJ:-KbF9-EkNNmtluuumPdD:bmlgdju) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/backup.js#L22)):*
> ```JavaScript
>       const oldUserName = this.userName;
>       this.userName = name;
>       this.addUserNames(this.userName);
> ```

addUserNames が2回あるので片方を消しましょ

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Review status: 3 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[js/backup.js, line 46 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF991wEc0SIneNkJU_:-KbF991wEc0SIneNkJUa:b-y8jhi) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/backup.js#L46)):*
> ```JavaScript
>     });
>   }
>   restore() {
> ```

setEmptyBlock をなくして、
restore 内で、blockManagerModel.clear みたいな関数を作るとかどうですか？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by dadaa** [comment]
Review status: 3 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[js/backup.js, line 9 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF_Ec3jm_YIJUPKscq:-KbF_Ec3jm_YIJUPKscr:b-crzpud) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/backup.js#L9)):*
> ```JavaScript
> 
>     eventPublisher.subscribe("updateMotion", (index, motion) => {
>       const backup = this.contains(this.userName, index) ? this.get(this.userName, index) : this.getEmptyData();
> ```

`this.userName = localStorage.getItem("controller-name");`
のように userName を取っているのをみると、一つのインスタンスで複数の userName のバックアップは取らないように見えるので、this.contains などは index だけで良いように思ったのですが、違うかしら？
もし複数のバックアップを取るのであれば、this.userName とはしない＆localStorageから持ってくるより良い方法がありそうな気がします。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by nakamurataichi** [comment]
*[js/components/change-user-screen.vue, line 6 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF6QRZa6qwqbVPRma6:-KbHNByR7GplJ0PvipIF:b-p34fh7) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/components/change-user-screen.vue#L6)):*
<details><summary><i>Previously, shundroid wrote…</i></summary><blockquote>

document.get..... を使わない方法・・

↓の data() のところの return で、userName とかいう state を追加します。
`userName: ""` みたいな

それで、↑の要素に、 `v-model="userName"` という感じで属性を指定します。

そうすると、双方向にデータバインディングをしてくれるので、要素を参照する必要がなくなります。

https://jp.vuejs.org/v2/guide/forms.html
</blockquote></details>

ありがとうございます、修正しました

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by nakamurataichi** [comment]
*[js/backup.js, line 9 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF_Ec3jm_YIJUPKscq:-KbHKJAXSm8p7qdsw2R7:bn53q28) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/backup.js#L9)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

`this.userName = localStorage.getItem("controller-name");`
のように userName を取っているのをみると、一つのインスタンスで複数の userName のバックアップは取らないように見えるので、this.contains などは index だけで良いように思ったのですが、違うかしら？
もし複数のバックアップを取るのであれば、this.userName とはしない＆localStorageから持ってくるより良い方法がありそうな気がします。
</blockquote></details>

そうですね、直します。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by nakamurataichi** [comment]
*[js/backup.js, line 9 at r3](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbF_Ec3jm_YIJUPKscq:-KbJqo7wwC_T_yv7ziGs:bb04hu4) ([raw file](https://github.com/comozilla/onigo-controller/blob/b14d7dc6bc4cd931eb5a0922b28e1192698ddd7e/js/backup.js#L9)):*
<details><summary><i>Previously, nakamurataichi (taichi) wrote…</i></summary><blockquote>

そうですね、直します。
</blockquote></details>

clearBackup() するときに、どうしても別のユーザー名で indexes を取得する必要があったので、
getIndexes() 以外の name 引数を消してみました

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Review status: 2 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[js/backup.js, line 19 at r4](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbKQUml4bEn39l9ln0t:-KbKQUml4bEn39l9ln0u:b-p09mal) ([raw file](https://github.com/comozilla/onigo-controller/blob/38b41bc7451c7af07155c07bebe11c4de1d834b2/js/backup.js#L19)):*
> ```JavaScript
>       this.set(index, backup);
>     });
>     eventPublisher.subscribeModel("userName", name => {
> ```

subscribeModel は、model に対して行うので、
普通の subscribe にしてください

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Reviewed 1 of 5 files at r4.
Review status: 3 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Review status: 3 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[js/components/change-user-button.vue, line 12 at r4](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbKZp0OgDm0f11PyVLR:-KbKZp0OgDm0f11PyVLS:b-a9abob) ([raw file](https://github.com/comozilla/onigo-controller/blob/38b41bc7451c7af07155c07bebe11c4de1d834b2/js/components/change-user-button.vue#L12)):*
> ```Vue
>   methods: {
>     showLoginForm() {
>       appModel.changeOpeningMotionId(-1);
> ```

これはなぜ必要ですか？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Reviewed 1 of 5 files at r4.
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[js/backup.js, line 52 at r4](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbKZwXLjHR5D8cD8vLD:-KbKZwXLjHR5D8cD8vLE:bbp5imy) ([raw file](https://github.com/comozilla/onigo-controller/blob/38b41bc7451c7af07155c07bebe11c4de1d834b2/js/backup.js#L52)):*
> ```JavaScript
>     return JSON.parse(localStorage.getItem(`${this.userName}-backup-${index}`));
>   }
>   addUserNames(name) {
> ```

今更でごめんなさいなんですけど、
addUserNames だと、引数を配列で渡す感じがするので、
`addToUserNames` とか `addUserName` とかがいいかと思います。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Reviewed 1 of 5 files at r4.
Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by nakamurataichi** [comment]
*[js/components/change-user-button.vue, line 12 at r4](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbKZp0OgDm0f11PyVLR:-KbK_7c9c_1apl6HZPaR:b4szq5c) ([raw file](https://github.com/comozilla/onigo-controller/blob/38b41bc7451c7af07155c07bebe11c4de1d834b2/js/components/change-user-button.vue#L12)):*
<details><summary><i>Previously, shundroid wrote…</i></summary><blockquote>

これはなぜ必要ですか？
</blockquote></details>

editor を出している状態でボタンを押すと、 editor の下にユーザー切り替えスクリーンが出て、
editor にボタンが隠れてしまったので、強制的に閉じるようにしました

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Reviewed 1 of 5 files at r4.
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[js/components/change-user-button.vue, line 12 at r4](https://reviewable.io:443/reviews/comozilla/onigo-controller/45#-KbKZp0OgDm0f11PyVLR:-KbKa3Jd1LuUV1D3DCO3:b-fc6ik1) ([raw file](https://github.com/comozilla/onigo-controller/blob/38b41bc7451c7af07155c07bebe11c4de1d834b2/js/components/change-user-button.vue#L12)):*
<details><summary><i>Previously, nakamurataichi (taichi) wrote…</i></summary><blockquote>

editor を出している状態でボタンを押すと、 editor の下にユーザー切り替えスクリーンが出て、
editor にボタンが隠れてしまったので、強制的に閉じるようにしました
</blockquote></details>

あー、editor の z-index の問題か・・
別の時に直しましょう
わかりました

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Reviewed 1 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Comment by shundroid** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-controller/45)*

**Pull request merged**
